moscow/moscow/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('search.urls')),
]

moscow/search/urls.py
from django.conf.urls import url
from .views import *

from . import views

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^log_in$', log_in, name='log_in'),
    url(r'^log_out$', log_out, name='log_out'),
    url(r'^register$', register, name='register'),
    url(r'^main$', main, name='main'),
    url(r'^account/(?P<username>[\w.@+-]+)$', account, name='account'),
    url(r'^place/(?P<place_id>[0-9]+)$', place, name='place'),
    url(r'^add_review/(?P<place_id>[0-9]+)$', add_review, name='add_review'),
    url(r'^change_review/(?P<review_id>[0-9]+)$', change_review, name='change_review'),
    url(r'^del_review/(?P<review_id>[0-9]+)$', del_review, name='delete_review'),
    url(r'^add_tags/(?P<place_id>[0-9]+)$', add_tags, name='add_tags'),
]

moscow/search/models.py
from django.db import models
from django.contrib.auth.models import User

class District(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Underground_station(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE, related_name='stations')
    name = models.CharField(max_length=100)
    coordinates = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    place = models.ForeignKey("Place", on_delete=models.CASCADE)
    text = models.TextField()
    rating = models.PositiveIntegerField()

    def __str__(self):
        return "Review by {}".format(self.author.username)


class Place(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    coordinates = models.CharField(max_length=100)
    working_hours = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag)
    underground_stations = models.ManyToManyField(Underground_station)
    num_reviews = models.PositiveIntegerField(default=0)
    sum_rating = models.PositiveIntegerField(default=0)

    def before_new_review(self, review, old_rating=None):
        try:
            last_review = Review.objects.filter(author=review.author, place=self).latest("pk")
        except Review.DoesNotExist:
            last_review = None

        if old_rating is None:
            if last_review is None:
                self.num_reviews += 1
                self.sum_rating += review.rating
            else:
                self.sum_rating += review.rating - last_review.rating
        else:
            if review.pk == last_review.pk:
                self.sum_rating += review.rating - old_rating

        self.save()

    def after_del_review(self, review, old_pk):
        try:
            last_review = Review.objects.filter(author=review.author, place=self).latest("pk")
        except Review.DoesNotExist:
            self.num_reviews -= 1
            self.sum_rating -= review.rating
        else:
            if old_pk > last_review.pk:
                self.sum_rating -= review.rating - last_review.rating

        self.save()

    def average_rating(self):
        return round(self.sum_rating / self.num_reviews) if self.num_reviews else 0

    def __str__(self):
        return self.name

moscow/search/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.views.decorators.http import require_POST
from django.utils.http import is_safe_url
from django.db.models import Q
from .models import *

import heapq


def redirect_back(request, *args):
    redirect_to = request.POST.get('next', request.GET.get('next'))

    if redirect_to is not None and is_safe_url(url=redirect_to, host=request.get_host()):
        return redirect(redirect_to)
    else:
        return redirect(*args)


def index(request):
    return render(request, 'index.html', {'stations': Underground_station.objects.all(), 'districts': District.objects.all(), 'tags': Tag.objects.all()})


def log_in(request):
    if request.user.is_authenticated():
        return render(request, 'login.html', {'error': 'Вы уже авторизованы!'})
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        if User.objects.filter(username=username).exists():
            logout(request)
            user = authenticate(username=username, password=password)
            if user is None:
                return render(request, 'login.html', {'error': 'Неправильный пароль!'})
            login(request, user)
            return redirect('index')
        else:
            return render(request, 'login.html', {'error': 'Пользователь с таким именем не существует!'})
    return render(request, 'login.html')


@require_POST
def log_out(request):
    logout(request)
    return redirect('index')


def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    elif request.method == 'POST':
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        if not User.objects.filter(username=username).exists():
            user = User.objects.create_user(username=username, password=password)
            user.save()
            logout(request)
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('index')
        else:
            return render(request, 'register.html', {'error': 'Такой пользователь уже существует!'})
    return render(request, 'register.html')


def account(request, username):
    subject = get_object_or_404(User, username=username)
    return render(request, 'account.html', {'subject': subject})


def dist(x1, y1, x2, y2):
    return (x1 - x2)**2 + (y1 - y2)**2

def parse_coords(coordinates):
    return map(float, coordinates[1:-1].split(", "))



def main(request):
    selected_stations = request.POST.getlist('stations[]') # Выбранные пользователем станции метро; может быть пустым
    selected_district = request.POST.get('district') # Выбранный пользователем район, может быть None
    selected_tags = request.POST.getlist('tags[]') # Выбранные пользователем теги; может быть пустым
    x, y = request.POST.get('x'), request.POST.get('y') # Координаты пользователя

    q_district = Q(district__name=selected_district)

    q_tags = Q(tags__name__in=selected_tags)

    q_stations = Q(name__in=selected_stations)
    h = []
    q_res = Q()
    if not selected_stations and not selected_district: # Нет заданныйх районов поиска
    
        if x and y: # Есть координаты пользователя
            x = float(x); y = float(y)
            for place in Place.objects.all():
                px, py = parse_coords(place.coordinates)
                heapq.heappush(h, (dist(px, py, x, y), place.coordinates))
            q = [t[1] for t in heapq.nsmallest(100, h)]
            q_res = Q(coordinates__in=q)

    else:
        q_res = q_district
        if selected_stations:
            places = Place.objects.all()
            for stations in Underground_station.objects.filter(q_stations).all():
                y, x = parse_coords(stations.coordinates) # коорднаты для станций в другом порядке
                for place in places:
                    px, py = parse_coords(place.coordinates)
                    heapq.heappush(h, (dist(px, py, x, y), place.coordinates))
                
            q = [t[1] for t in heapq.nsmallest(100, h)]
            q_res = q_res | Q(coordinates__in=q)
            

    if not selected_tags:
        places = Place.objects.filter(q_res).all()[:100]
    else:
        places = Place.objects.filter(q_res & q_tags).all()[:100]
    
    if not places:
        return render(request, 'main.html')

    ystaticmap = 'https://static-maps.yandex.ru/1.x/?l=map&size=650,450&pt='
    i = 1
    for place in places:
        x, y = parse_coords(place.coordinates)
        ystaticmap += str(x) + ',' + str(y) + ',pmrdl'+ str(i) +'~'
        i += 1
    ystaticmap = ystaticmap[:-1]

    return render(request, 'main.html', {'map': True, 'ystaticmap': ystaticmap, 'places': places})


def place(request, place_id):
    place = get_object_or_404(Place, pk=place_id)
    return render(request, 'place.html', {'place': place, 'stations': [station.name for station in place.underground_stations.all()]})

@login_required
def add_review(request, place_id):
    place = get_object_or_404(Place, pk=place_id)

    if request.method == "POST":
        text = request.POST.get('text')
        rating = request.POST.get('rating')
        if rating == '':
            rating = "1"
        review = Review(author=request.user, place=place, text=text, rating=int(rating))
        review.place.before_new_review(review)
        review.save()
        return redirect_back(request, 'place', place.pk)
    else:
        return render(request, 'add_review.html', {'place': place})


@login_required
def change_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if review.author != request.user:
        raise PermissionDenied

    if request.method == "POST":
        review.text = request.POST.get('text')
        old_rating = review.rating
        review.rating = int(request.POST.get('rating'))
        review.place.before_new_review(review, old_rating)
        review.save()
        return redirect_back(request, 'account', review.author.username)
    else:
        return render(request, 'change_review.html', {'review': review})


@require_POST
@login_required
def del_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if review.author != request.user:
        raise PermissionDenied

    old_pk = review.pk
    review.delete()
    review.place.after_del_review(review, old_pk)
    return redirect_back(request, 'account', review.author.username)


@login_required
def add_tags(request, place_id):
    place = get_object_or_404(Place, pk=place_id)

    if request.method == "POST":
        tags = request.POST.get('added_tags')
        if tags is not None:
            tags = tags.split("; ")
            for tag in tags:
                sep = tag.find(":")
                if sep == -1:
                    tag, created = Tag.objects.get_or_create(name=tag)
                else:
                    parent = tag[0:sep]
                    tag = tag[sep+1:]

                    if not Tag.objects.filter(name=parent).exists():
                        tag = None
                    elif Tag.objects.filter(name=tag).exists():
                        tag = Tag.objects.get(name=tag)
                    else:
                        tag = Tag(name=tag, parent=Tag.objects.get(name=parent))
                        tag.save()

                if tag is not None:
                    place.tags.add(tag)
                    tag.users.add(request.user)

        return redirect_back(request, 'place', place.pk)
    else:
        return render(request, 'add_tags.html', {'tags': Tag.objects.all(), 'place': place})

moscow/search/templates/account.html
{% extends "base.html" %}
{% block title %} Профиль {{ subject.username }} {% endblock %}
{% block content %}
<style type="text/css">
.column {
  display: flex;
  flex-direction: column;
  justify-content: center;
  max-width:500px;
}
.buttons {
  display: flex;
  flex-direction: row;
}
.review-text {
  background-color: #AFEEEE;
}
</style>
<div class="container-fluid">
  <h2>Профиль {{ subject.username}}</h2>

  <span>Добавленные теги: {% for tag in subject.tag_set.all %} #{{ tag.name }} {% endfor %}</span>
  <div class="column">
  <span>Отзывы {{ subject.username }}:</span>
  {% for review in subject.review_set.all %}
    <h3>Отзыв на <a href="{% url 'place' review.place.pk %}">&laquo;{{ review.place.name }}&raquo;</a></h3>
    <span class="review-text"> {{ review.text}} </span>
    <span> Оценка:
      {% with ''|center:review.rating as range %}
      {% for _ in range %}
      <span class="glyphicon glyphicon-star" style="color: #FFFF00"></span>
      {% endfor %}
      {% endwith %}
    </span>
    {% if user == subject %}
      <div class="buttons">
        <form action="{% url 'change_review' review.pk %}" method="get">
          <input type="hidden" name="next" value="{{ request.path }}">
          <button class="btn btn-info"> Изменить отзыв </button>
        </form> &nbsp;&nbsp;
        <form action="{% url 'delete_review' review.pk %}" method="post"> {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <button class="btn btn-info"> Удалить отзыв </button>
        </form>
      </div>
    {% endif %}
  {% endfor %}
  </div>
</div>
{%endblock%}

moscow/search/templates/add_review.html
{% extends "base.html" %}
{% block title %} Добавить отзыв {% endblock %}
{% block content %}
<style type="text/css">
.text {
  overflow: auto;
  width: 500px;
}
.glyphicon-star {
  color: #FFFF00;
  cursor: pointer;
}
</style>
<div class="container-fluid">
<form action="{% url 'add_review' place.pk %}" method="post"> {% csrf_token %}
<fieldset class="form-group">
  <div class="text">
    Ваш отзыв на <a href="{% url 'place' place.pk %}">&laquo;{{ place.name }}&raquo;</a>:
    <textarea class="form-control" rows="10" name="text"></textarea>
  </div>
  <div>
    Ваша оценка заведения:
    {% with ''|center:5 as range %}
    {% for _ in range %}
    <div class="glyphicon glyphicon-star" id="star_{{ forloop.counter }}"></div>
    {% endfor %}
    {% endwith %}
  </div>
  <input type="hidden" name="rating" id="rating_input" value="{{ review.rating }}">
  <input type="hidden" name="next" value="{{ request.GET.next }}">
  <button type="submit" class="btn btn-info"> Отправить отзыв </button>
</fieldset>
</form>
Вы можете в любой момент изменить свой отзыв в своём <a href="{% url 'account' user.username %}">личном кабинете</a>.
</div>
<script type="text/javascript">
  $(document).ready(function(){
    function displayRating(rating) {
      for (index = 1; index <= 5; index++) {
        var star = $("#star_" + index.toString());

        if (index <= rating) {
          star.css('color', '#FF4500');
        } else {
          star.css('color', '#FFFF00');
        }
      }
    }

    $(".glyphicon-star").each(function(index) {
      var this_index = index + 1;
      var this_star = $("#star_" + this_index.toString());

      this_star.mouseenter(function() {
        displayRating(this_index);
      });

      this_star.mouseleave(function() {
        var rating = parseInt($("#rating_input").val());
        displayRating(rating);
      });

      this_star.click(function() {
        $("#rating_input").val(this_index.toString());
      });
    });

    displayRating({{ review.rating }});
  });
</script>
{% endblock %}

moscow/search/templates/add_tags.html
{% extends "base.html" %}
{% block title %} Добавить теги {% endblock %}
{% block content %}
<style type="text/css">
.tag {
    width: 300px;
    maxlength: 100;
}
#tag_parent_val {
    max-height: 200px;
    overflow: auto;
}
label {
    font-weight: normal;
}
input[type="radio"] {
    margin: 0;
}
.long {
  max-height: 200px;
  overflow: auto;
  width: auto;
}​
</style>
<script type="text/javascript">
  function addTagSon() {
    tag_son = $("#tag_son_val").val();
    tag_parent = $('input[name="tag_parent"]:checked').val();
    if (tag_parent) {
      $("#tag_son_val").val("");
      tag = tag_parent + ":" + tag_son;
      var added_tags = $("#added_tags");
      var old_value = added_tags.val();
      if (old_value === "") {
        added_tags.val(tag);
        var for_remove = $("#for_remove");
        var old_remove = for_remove.html();
        for_remove.html(old_remove + '<div id="remove_' + tag + '"> <input type="radio" name="remove_tag" value="' + tag + '"> ' + tag + ' </div>');
      } else {
        start = old_value.indexOf(tag + ";");
        if (start == -1 && old_value.lastIndexOf(tag) + tag.length == old_value.length) {
          start = old_value.lastIndexOf(tag);
        }
        if (start == -1) { // Можно добавлять тег
          added_tags.val(old_value + "; " + tag);
          var for_remove = $("#for_remove");
          var old_remove = for_remove.html();
          for_remove.html(old_remove + '<div id="remove_' + tag + '"> <input type="radio" name="remove_tag" value="' + tag + '"> ' + tag + ' </div>');
        }
      }
    }
  }
</script>
<script type="text/javascript">
  $(document).ready(function(){
    function addTag(tag) {
      var added_tags = $("#added_tags");
      var old_value = added_tags.val();
      if (old_value === "") {
        added_tags.val(tag);
        var for_remove = $("#for_remove");
        var old_remove = for_remove.html();
        for_remove.html(old_remove + '<div id="remove_' + tag + '"> <input type="radio" name="remove_tag" value="' + tag + '"> ' + tag + ' </div>');
      } else {
        start = old_value.indexOf(tag + ";");
        if (start == -1 && old_value.lastIndexOf(tag) + tag.length == old_value.length) {
          start = old_value.lastIndexOf(tag);
        }
        if (start == -1) { // Можно добавлять тег
          added_tags.val(old_value + "; " + tag);
          var for_remove = $("#for_remove");
          var old_remove = for_remove.html();
          for_remove.html(old_remove + '<div id="remove_' + tag + '"> <input type="radio" name="remove_tag" value="' + tag + '"> ' + tag + ' </div>');
        }
      }
    }

    $("#new_tag").click(function() {
      tag = $("#new_tag_val").val();
      $("#new_tag_val").val("");
      addTag(tag);
    });

    $("#old_tag").click(function() {
      tag = $('input[name="old_tag"]:checked').val();
      addTag(tag);
    });

    $("#del_tag").click(function() {
      tag = $('input[name="remove_tag"]:checked').val();
      colon = tag.indexOf(":");
      if (colon == -1) {
        $("#remove_"+tag).remove();
      } else {
        $("#remove_"+tag.substr(0, colon)+"\\"+tag.substr(colon)).remove();
      }
      all_tags = $('#added_tags').val();
      start = all_tags.indexOf(tag + ";");
      if (start == -1) {
        start = all_tags.lastIndexOf(tag);
      }
      end = start + tag.length + 2;
      if (start == 0) {
        all_tags = all_tags.substr(0, start) + all_tags.substr(end, all_tags.length);
      } else {
        start = start - 2; end = end - 2;
        all_tags = all_tags.substr(0, start) + all_tags.substr(end, all_tags.length);
      }
      $('#added_tags').val(all_tags);
    });
  });
</script>
<div class="container-fluid">
  <div>
    Добавление тегов для <a href="{% url 'place' place.pk %}">&laquo;{{ place.name }}&raquo;</a>:<br>
    Вы можете либо добавить новый тег, либо добавить тег-потомок имеющегося, либо удалить нечаянно добавленный тег: и так много раз!
    <br> Когда Вы выберете все теги, нажмите большую кнопку "Добавить теги". Названия тегов не должны содержать двоеточий и точек с запятой!
  </div>
  Выберите тег из уже имеющихся:
    <div id="tag_parent_val" class="long">
      {% for tag in tags %}
        <div><input type="radio" id="old_rbtn_{{ tag.pk }}" name="old_tag" value="{{ tag }}"><label for="old_rbtn_{{ tag.pk }}">{{ tag }}</label></div>
      {% endfor %}
      <input value="Добавить тег" id="old_tag" type="button" class="btn btn-info btn-sm">
    </div>
  <br>
  <div>
    Добавить новый тег: <br>
    <input type="text" class="tag" id="new_tag_val">
    <input value="Добавить новый тег" id="new_tag" type="button" class="btn btn-info btn-sm">
  </div>
  <br>
  <div>
  <form action="javascript:addTagSon()">
    Выбрать, к какому из имеющихся тегов добавить тег-потомок:
    <div id="tag_parent_val" class="long">
      {% for tag in tags %}
        <div><input type="radio" id="new_rbtn_{{ tag.pk }}" name="tag_parent" value="{{ tag }}"><label for="new_rbtn_{{ tag.pk }}">{{ tag }}</label></div>
      {% endfor %}
    </div>
    <div>
      Добавить тег-потомок: <br>
      <input type="text" class="tag" id="tag_son_val">
      <button id="tag_son" class="btn btn-info btn-sm" type="submit"> Добавить тег-потомок </button>
    </div>
  </form>
  </div>
  <br>
  <div>
    Удалить ошибочно добавленный тег:
    <div id="for_remove">
    </div>
    <input value="Удалить тег" id="del_tag" type="button" class="btn btn-info btn-sm">
  </div>
  <br>
  <div>
    Уже добавленные теги:
    <form id="myform" action="{% url 'add_tags' place.pk %}" method="post"> {% csrf_token %}
      <textarea rows="5" class="tag" name="added_tags" id="added_tags"></textarea> <br>
      <input type="hidden" name="next" value="{{ request.GET.next }}">
      <button class="btn btn-lg btn-info" type="submit"> Добавить теги </button>
    </form>
  </div>
</div>
{% endblock %}

moscow/search/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title> {% block title %} Поиск мест, где можно поразвлечься в Москве {% endblock %} </title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style type="text/css">
    body {
      background-color: #B0E0E6;
    }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" style="color: white" href="{% url 'index' %}">На главную</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          {% if user.is_authenticated %}
          <form class="navbar-form navbar-right" action="{% url 'account' user.username %}">
            <button type="submit" class="btn btn-info"> Личный кабинет </button>
          </form>
          <form class="navbar-form navbar-right" action="{% url 'log_out' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-info"> Выйти </button>
          </form>
          {% else %}
          <form class="navbar-form navbar-right" action="{% url 'log_in' %}">
            <button type="submit" class="btn btn-info"> Войти </button>
          </form>
          <form class="navbar-form navbar-right" action="{% url 'register' %}">
             <button type="submit" class="btn btn-info"> Зарегистрироваться </button>
          </form>
          {% endif %}
       </div>
      </div>
    </nav>
    {%block content%} {%endblock%}
  </body>
</html>

moscow/search/templates/change_review.html
{% extends "base.html" %}
{% block title %} Изменить отзыв {% endblock %}
{% block content %}
<style type="text/css">
.text {
  overflow: auto;
  width: 500px;
}
.glyphicon-star {
  color: #FFFF00;
  cursor: pointer;
}
</style>
<div class="container-fluid">
<form action="{% url 'change_review' review.pk %}" method="post"> {% csrf_token %}
<fieldset class="form-group">
  <div class="text">
    Ваш отзыв на <a href="{% url 'place' review.place.pk %}">&laquo;{{ review.place.name }}&raquo;</a>:
    <textarea class="form-control" rows="10" name="text">{{ review.text }}</textarea>
  </div>
  <div>
    Ваша оценка заведения:
    {% with ''|center:5 as range %}
    {% for _ in range %}
    <div class="glyphicon glyphicon-star" id="star_{{ forloop.counter }}"></div>
    {% endfor %}
    {% endwith %}
  </div>
  <input type="hidden" name="rating" id="rating_input" value="{{ review.rating }}">
  <input type="hidden" name="next" value="{{ request.GET.next }}">
  <button type="submit" class="btn btn-info"> Изменить отзыв </button>
</fieldset>
</form>
Вы можете в любой момент изменить свой отзыв в своём <a href="{% url 'account' user.username %}">личном кабинете</a>.
</div>
<script type="text/javascript">
  $(document).ready(function(){
    function displayRating(rating) {
      for (index = 1; index <= 5; index++) {
        var star = $("#star_" + index.toString());

        if (index <= rating) {
          star.css('color', '#FF4500');
        } else {
          star.css('color', '#FFFF00');
        }
      }
    }

    $(".glyphicon-star").each(function(index) {
      var this_index = index + 1;
      var this_star = $("#star_" + this_index.toString());

      this_star.mouseenter(function() {
        displayRating(this_index);
      });

      this_star.mouseleave(function() {
        var rating = parseInt($("#rating_input").val());
        displayRating(rating);
      });

      this_star.click(function() {
        $("#rating_input").val(this_index.toString());
      });
    });

    displayRating({{ review.rating }});
  });
</script>
{% endblock %}

moscow/search/templates/login.html
{% extends "base.html" %}
{% block title %} Вход {% endblock %}
{% block content %}
<style type="text/css">
.form-signin {
  max-width: 380px;
  padding: 15px 35px 45px;
  margin: 0 auto;
}
.form-signin-heading {
  text-align: center;
}
</style>
<div class="container-fluid">
    <form class="form-signin" method="post"> {% csrf_token %}
      <div class="form-signin-heading"> {{ error }} </div>
      <h2 class="form-signin-heading"> Войти </h2>
      <input type="text" class="form-control" name="username" placeholder="your name" required="" autofocus="" />
      <input type="password" class="form-control" name="password" placeholder="password" required=""/>
      <button class="btn btn-primary btn-block" type="submit"> Войти </button>
    </form>
</div>
{%endblock%}

moscow/search/templates/place.html
{% extends "base.html" %}
{% block title %}{{ place.name }}{% endblock %}
{% block content %}
<style type="text/css">
.column {
  display: flex;
  flex-direction: column;
  justify-content: center;
  max-width:500px;
}
.buttons {
  display: flex;
  flex-direction: row;
}
.review-text {
  background-color: #AFEEEE;
}
</style>
<div class="container-fluid">
  <h2>&laquo;{{ place.name }}&raquo;</h2>

  <div class="column">
    <h3>Информация:</h3>
    <ul>
      <li>Район: {{ place.district.name }}</li>
      <li>Метро: {{ stations|join:", " }}</li>
      <li>Часы работы: {{ place.working_hours }}</li>
      <li>Вебсайт: {{ place.website }}</li>
      <li>Телефон: {{ place.phone }}</li>
      <li>Теги: {% for tag in place.tags.all %} #{{ tag.name }} {% endfor %}</li>
      <li>Средний рейтинг: {% if place.num_reviews %}{{ place.average_rating }}{% else %}N/A{% endif %} ({{ place.num_reviews }} отзывов)
    </ul>

    {% if user.is_authenticated %}
      <div class="buttons">
        <form action="{% url 'add_review' place.pk %}" method="get">
          <input type="hidden" name="next" value="{{ request.path }}">
          <button type="submit" class="btn btn-info">Добавить отзыв</button>
        </form> &nbsp;&nbsp;
        <form action="{% url 'add_tags' place.pk %}" method="get">
          <input type="hidden" name="next" value="{{ request.path }}">
          <button type="submit" class="btn btn-info">Добавить теги</button>
        </form>
      </div>
    {% endif %}

    <h3>Отзывы:</h3>
    {% for review in place.review_set.all %}
      <span>Отзыв от <a href="{% url 'account' review.author.username %}">{{ review.author.username }}</a></span>
      <span class="review-text"> {{ review.text}} </span>
      <span> Оценка:
        {% with ''|center:review.rating as range %}
        {% for _ in range %}
        <span class="glyphicon glyphicon-star" style="color: #FFFF00"></span>
        {% endfor %}
        {% endwith %}
      </span>
      {% if user == review.author %}
        <div class="buttons">
          <form action="{% url 'change_review' review.pk %}" method="get">
            <input type="hidden" name="next" value="{{ request.path }}">
            <button class="btn btn-info"> Изменить отзыв </button>
          </form> &nbsp;&nbsp;
          <form action="{% url 'delete_review' review.pk %}" method="post"> {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <button class="btn btn-info"> Удалить отзыв </button>
          </form>
        </div>
      {% endif %}
    {% endfor %}
    </div>
</div>
{% endblock %}